# Generated by Django 4.1.3 on 2022-12-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='mark',
            field=models.PositiveSmallIntegerField(choices=[(1, 'awful'), (2, 'bad'), (3, 'average'), (4, 'good'), (5, 'excellent')], verbose_name='Rating'),
        ),
    ]
