# Generated by Django 4.1.3 on 2022-12-02 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_author_country_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(db_index=True, help_text='Correct ISBN format: (XXX-)XXXXXXXXXX. If prefix exists remove parenthesis', max_length=17, validators=[django.core.validators.RegexValidator(message='Please, see correct ISBN format above', regex='(?:\\d{3}-)?\\d{10}')], verbose_name='ISBN-10/13'),
        ),
    ]
