# Generated by Django 4.1.3 on 2022-12-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='author',
            name='about',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
