# Generated by Django 4.1.3 on 2022-12-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_genre_options_author_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
    ]
