# Generated by Django 4.1.3 on 2022-12-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-edited']},
        ),
    ]
